window.NOVABOX_PRODUCTS = [
    {
        id: 1,
        sku: "LED-001",
        supplierSku: "SUP-LED-001",
        name: "LED-светильник",
        category: "Электроника",
        price: 1290,
        oldPrice: 1590,
        stock: 12,
        image: "",
        desc: "Настольный светильник для работы, учёбы и дома.",
        brand: "NovaBox",
        status: "active",
        sourceType: "manual",
        updatedAt: "2026-06-24"
    },
    {
        id: 2,
        sku: "USB-001",
        supplierSku: "SUP-USB-001",
        name: "USB-хаб",
        category: "Электроника",
        price: 890,
        oldPrice: 1190,
        stock: 8,
        image: "",
        desc: "Компактный USB-хаб для ноутбука, ПК и рабочих устройств.",
        brand: "NovaBox",
        status: "active",
        sourceType: "manual",
        updatedAt: "2026-06-24"
    },
    {
        id: 3,
        sku: "PHONE-001",
        supplierSku: "SUP-PHONE-001",
        name: "Подставка для телефона",
        category: "Аксессуары",
        price: 490,
        oldPrice: 690,
        stock: 20,
        image: "",
        desc: "Удобная настольная подставка для смартфона.",
        brand: "NovaBox",
        status: "active",
        sourceType: "manual",
        updatedAt: "2026-06-24"
    },
    {
        id: 4,
        sku: "HOME-001",
        supplierSku: "SUP-HOME-001",
        name: "Мини-увлажнитель",
        category: "Для дома",
        price: 1490,
        oldPrice: 1890,
        stock: 6,
        image: "",
        desc: "Компактный увлажнитель воздуха для комнаты и рабочего места.",
        brand: "NovaBox",
        status: "active",
        sourceType: "manual",
        updatedAt: "2026-06-24"
    },
    {
        id: 5,
        sku: "LIGHT-001",
        supplierSku: "SUP-LIGHT-001",
        name: "Ночник",
        category: "Для дома",
        price: 790,
        oldPrice: 990,
        stock: 15,
        image: "",
        desc: "Мягкий свет для спальни, детской комнаты и рабочего стола.",
        brand: "NovaBox",
        status: "active",
        sourceType: "manual",
        updatedAt: "2026-06-24"
    },
    {
        id: 6,
        sku: "MOUSE-001",
        supplierSku: "SUP-MOUSE-001",
        name: "Коврик для мыши",
        category: "Аксессуары",
        price: 690,
        oldPrice: 890,
        stock: 18,
        image: "",
        desc: "Большой коврик для мыши, клавиатуры и комфортной работы.",
        brand: "NovaBox",
        status: "active",
        sourceType: "manual",
        updatedAt: "2026-06-24"
    },
    {
        id: 7,
        sku: "LAPTOP-001",
        supplierSku: "SUP-LAPTOP-001",
        name: "Подставка для ноутбука",
        category: "Аксессуары",
        price: 1690,
        oldPrice: 2190,
        stock: 5,
        image: "",
        desc: "Складная подставка для охлаждения и удобной работы за ноутбуком.",
        brand: "NovaBox",
        status: "active",
        sourceType: "manual",
        updatedAt: "2026-06-24"
    },
    {
        id: 8,
        sku: "STAND-001",
        supplierSku: "SUP-STAND-001",
        name: "Настольный штатив",
        category: "Новинки",
        price: 1190,
        oldPrice: 1490,
        stock: 9,
        image: "",
        desc: "Штатив для съёмки, стримов, видео и онлайн-занятий.",
        brand: "NovaBox",
        status: "active",
        sourceType: "manual",
        updatedAt: "2026-06-24"
    },
    {
        id: 9,
        sku: "CABLE-001",
        supplierSku: "SUP-CABLE-001",
        name: "Кабель Type-C",
        category: "Электроника",
        price: 390,
        oldPrice: 590,
        stock: 30,
        image: "",
        desc: "Кабель Type-C для зарядки и передачи данных.",
        brand: "NovaBox",
        status: "active",
        sourceType: "manual",
        updatedAt: "2026-06-24"
    },
    {
        id: 10,
        sku: "BOX-001",
        supplierSku: "SUP-BOX-001",
        name: "Органайзер для стола",
        category: "Для дома",
        price: 990,
        oldPrice: 1290,
        stock: 0,
        image: "",
        desc: "Органайзер для хранения мелочей, кабелей и аксессуаров.",
        brand: "NovaBox",
        status: "inactive",
        sourceType: "manual",
        updatedAt: "2026-06-24"
    }
];
